app:
  datasource:
    url: jdbc:postgresql://localhost:5432/charm_repository
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
    fetch-size: 50
    max-rows: 100
    query-timeout: 5
  base-content-path: /Users/andrey.s.eliseev/Downloads
